name: fitapp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1

  # SQL
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6         # desktop
  sqflite_common_ffi_web: ^0.4.5+4   # web (combina com o setup que você rodou)
  path_provider: ^2.1.3
  path: ^1.9.0

  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  archive: ^3.6.1
  file_picker: ^8.0.5
  image: ^4.1.7
  image_picker: ^1.0.7
  mobile_scanner: ^5.2.3

  muscle_selector:
    git:
      url: https://github.com/EmilCes/muscle_selector

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/exercise_db.json
    - assets/benchmarks.json
    - assets/taco.json
    - assets/muscle_front.svg
    - assets/muscle_back.svg
    - assets/prompts/
  # remova 'assets/i18n/' se a pasta não existir
