name: fitapp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3+1
  google_generative_ai: ^0.4.1
  dart_openai: ^5.1.0
  table_calendar: ^3.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  equatable: ^2.0.5
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  muscle_selector:
    git:
      url: https://github.com/EmilCes/muscle_selector
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/prompts/
    - assets/taco.json
