name: fitapp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    uses-material-design: true
  provider: ^6.1.2 
  # Banco de Dados Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  assets:
    - assets/prompts/
  # Conectividade e APIs
  dio: ^5.4.3+1 # Para chamadas HTTP
  google_generative_ai: ^0.4.1 # API do Gemini
  dart_openai: ^5.1.0 # API do OpenAI (GPT)
  table_calendar: ^3.1.2
  # UI & Utilidades
  provider: ^6.1.2 # Gerenciamento de estado simples
  intl: ^0.19.0 # Para formatação de datas
  fl_chart: ^0.68.0 # Para gráficos
  equatable: ^2.0.5 # Para comparação de objetos
  
  # Hardware & Sensores
  mobile_scanner: ^5.1.1 # Leitor de QR Code e Código de Barras
  image_picker: ^1.1.2 # Para pegar imagens da câmera/galeria
  
  # O mapa muscular que você pediu
  muscle_selector:
    git:
      url: https://github.com/EmilCes/muscle_selector

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9