name: fitapp
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  provider: ^6.1.2
  # Banco de Dados Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Conectividade e APIs
  dio: ^5.4.3+1
  google_generative_ai: ^0.4.1
  dart_openai: ^5.1.0
  table_calendar: ^3.1.2
  # UI & Utilidades
  intl: ^0.19.0
  fl_chart: ^0.68.0
  equatable: ^2.0.5
  collection: ^1.18.0
  uuid: ^4.4.0
  # Hardware & Sensores
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  # Mapa muscular
  muscle_selector:
    git:
      url: https://github.com/EmilCes/muscle_selector

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/benchmarks.json
    - assets/taco.json
    - assets/prompts/
